# Generated by Django 4.2 on 2024-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_red_code_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=40),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drivers Licence'), ('international_passport', 'International Passport')], max_length=140),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='kyc/default.jpg', upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('single', 'Single'), ('other', 'Other'), ('married', 'Married')], max_length=40),
        ),
    ]
