# Generated by Django 4.2 on 2024-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_kyc_identity_image_alter_kyc_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='stat',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('in-active', 'In-active'), ('active', 'Active')], default='in-active', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('international_passport', 'International Passport'), ('national_id_card', 'National ID Card'), ('drivers_licence', 'Drivers Licence')], max_length=140),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('married', 'Married'), ('other', 'Other'), ('single', 'Single')], max_length=40),
        ),
    ]
