# Generated by Django 4.2 on 2024-06-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_account_status_alter_kyc_identity_type_and_more'),
        ('core', '0002_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recieve_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciever_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever_account', to='account.account'),
        ),
    ]
